env:
  - YARN_GPG=no
matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "10"

    - os: linux
      language: node_js
      node_js: "10"
    
    - os: windows
      language: node_js
      node_js: "10"

script:
  - |
    node ./build/scripts/build.js

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
before_deploy:
  - mkdir ./dist_binary
  - node ./build/scripts/beforeDeploy.js
deploy:
  provider: releases
  api_key: 
    secure: xFb4VFXg6Gm8vPiya3Lx6ZMNZOQit4HgtO4GRqNJCfkBBw8kaEPcS3oAmn3F+ltU5ZVeH3/u74vWUj4qJhe1+dJZoKGDsZ+utsCLGGUozc4iXNUq7VY9hOBTzm9pezYZbPpb0rDk17Xekqulywn861O7vA0XYnUY+CX6/P7hBxhs0kO20nML6T7qxCn3VfF67my+CybOEhT76doNaYSwdXmBJlHjan8w6z7+lJn4VPoBP1216f1pAbEJ/EVuPluZibpLnCjDLTBKfyG6bFbKt02LMmKz8hr1xILBxd440a0oAqhwU3Th+0vimHi/jNWP7RNjkEPWFQnOsbvnyWFXixexYxJeep52/EmPFD1XD97aeEKTijFwRHjgnXKiE4IhHTRdQ23IFmIAM/hRRQMooe0AwLweYULcfoTUsjMG9wTt/c6uokKfpJsEc8+eLXaRFYFQMn8x0DOa6pQaY7eY4MgehKVpOyT4IYFK47JIm5hokKYQ3ik/kOe6Df9IW/9xmja6KP1IMbyQ1U9wy3sy6MlM8STouXRRbgW2XSVIRGYSuPn1V/1HMN+B7gd9N31QRO9OI7AcRJvJ+rn6yEHPZjH2rEEL1SMDLWSsb8Ox8wUoYhKX1nMDu6mwBWttJWM2lvWx1LlLJMYn4RKwxSFhYDn3kMIwyd8RSnkNotn8TGM=
  file_glob: true
  file: dist_binary/*
  skip_cleanup: true
  on:
    tags: true
  draft: true